"""Plain-text export."""

from __future__ import annotations

from app.generators.layout import (
    BODY_FONT_SIZE,
    LINE_SPACING,
    SIGNATURE_FIELDS,
)
from app.models import BrandProfile, Document
from app.schemas.ai import DocumentContent
from app.templates.disclaimer import EXPORT_DISCLAIMER

DIVIDER = "=" * 78
RULE = "-" * 78


def _wrap(text: str, width: int = 78) -> str:
    import textwrap

    out: list[str] = []
    for block in (text or "").split("\n"):
        if not block.strip():
            out.append("")
            continue
        out.extend(textwrap.wrap(block, width=width, break_long_words=False) or [""])
    return "\n".join(out)


def build_txt(
    document: Document, content: DocumentContent, brand: BrandProfile | None
) -> str:
    """Render a clean, readable plain-text rendering of the document."""
    lines: list[str] = []

    if brand and (brand.organization_name or brand.logo_path):
        if brand.organization_name:
            lines.append(brand.organization_name)
        contact = " | ".join(
            part for part in (brand.address, brand.email, brand.phone, brand.website) if part
        )
        if contact:
            lines.append(contact)
        lines.append(RULE)
        lines.append("")

    lines.append(DIVIDER)
    lines.append(content.title.center(78))
    lines.append(DIVIDER)
    lines.append("")

    if brand and brand.organization_name:
        lines.append(f"Prepared by: {brand.organization_name}")
    if content.generation and content.generation.generated_at:
        lines.append(f"Generated: {content.generation.generated_at[:10]}")
    if document.effective_date:
        lines.append(f"Effective date: {document.effective_date.isoformat()}")
    if document.jurisdiction:
        lines.append(f"Jurisdiction: {document.jurisdiction}")
    lines.append("")

    if content.intro:
        lines.append("INTRODUCTION")
        lines.append(RULE)
        lines.append(_wrap(content.intro))
        lines.append("")

    for section in content.sections:
        lines.append(section.heading.upper())
        lines.append(RULE)
        if section.content:
            lines.append(_wrap(section.content))
        for bullet in section.bullets:
            lines.append("")
            for i, part in enumerate(_wrap(bullet, 72).split("\n")):
                lines.append(f"  - {part}" if i == 0 else f"    {part}")
        if section.table:
            table = section.table
            if table.caption:
                lines.append("")
                lines.append(f"  {table.caption}")
            if table.headers:
                lines.append("")
                lines.append("  " + " | ".join(table.headers))
                lines.append("  " + "-" * min(70, sum(len(h) + 3 for h in table.headers)))
            for row in table.rows:
                lines.append("  " + " | ".join(str(cell) for cell in row))
        lines.append("")

    if content.signature_blocks:
        lines.append("SIGNATURES")
        lines.append(RULE)
        lines.append("")
        for block in content.signature_blocks:
            lines.append(f"For and on behalf of: {block.party_label}")
            if block.role:
                lines.append(f"Capacity: {block.role}")
            lines.append("")
            for field in block.fields or SIGNATURE_FIELDS:
                lines.append(f"  {field + ':':<16}{'_' * 40}")
            lines.append("")

    lines.append(RULE)
    lines.append(_wrap(content.disclaimer or EXPORT_DISCLAIMER, 78))
    lines.append("")

    if brand and brand.footer_text:
        lines.append(brand.footer_text)
        lines.append("")

    lines.append(
        f"Generated by LegalEase - AI-assisted document drafting "
        f"(body text {BODY_FONT_SIZE}pt, line spacing {LINE_SPACING})."
    )

    return "\n".join(lines) + "\n"
